name: IA GENERATIVE Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username:  ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Generate IMAGE AND PUSH 
      run: |
          docker build -t ia-generative .
          docker tag ia-generative matamou/ia-generative:latest
          docker push matamou/ia-generative:latest
